name: devops app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: List files
        run: echo "lenry is teaching"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install flake8

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.sha }}
      
      - name: Deploy to Azure Web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sakthiWeb'
          publish-profile: ${{ secrets.AZURE_PUBLISH }}
          images: '${{ secrets.DOCKER_USERNAME }}/devops:${{ github.sha }}'